import type { SupabaseClient } from '@supabase/supabase-js'
import { v4 as uuidv4 } from 'uuid'
import { DEADLINES } from './deadlines'
import { isIdempotentEnabled, type IdempotentRpc } from './featureFlags'
import { runWithDeadline } from './runWithDeadline'

/**
 * Classify an RPC error as transient (recoverable via offline queue retry)
 * vs permanent (auth/schema/business-logic — surfaces to user).
 *
 * Used by callers to decide whether to silently queue (sync_status='pending')
 * or mark-failed (sync_status='failed' → red banner). The latter should be
 * reserved for errors the user actually needs to act on.
 *
 * Transient indicators:
 *   - DEADLINE_EXCEEDED — the runWithDeadline timeout
 *   - OFFLINE_QUEUED   — the executeWithFallback queue handoff
 *   - PostgREST/network: code 'PGRST*' on its own can be either; we treat
 *     fetch/network/timeout messages as transient
 *   - No error object at all (raw fetch failure)
 *   - Common JS network errors: 'Network request failed', 'fetch failed',
 *     'TypeError: Failed to fetch'
 */
export function isTransientRpcError (err: unknown): boolean {
  if (!err) return false
  const e = err as { code?: string; message?: string; name?: string }
  if (e.code === 'DEADLINE_EXCEEDED') return true
  if (e.code === 'OFFLINE_QUEUED') return true
  // PostgREST timeout/connect errors typically have status 0 or a network message
  const msg = (e.message || '').toLowerCase()
  if (
    msg.includes('network') ||
    msg.includes('fetch') ||
    msg.includes('timeout') ||
    msg.includes('aborted') ||
    msg.includes('socket') ||
    msg.includes('econnreset') ||
    msg.includes('etimedout')
  ) return true
  if (e.name === 'AbortError') return true
  return false
}

/**
 * Resolves the UUID to pass as `p_idempotency_key` for a Category B RPC call.
 *
 * Reuse priority (avoids parallel key mechanisms):
 *   1. paymentJournalKey — for `process_payment`, reuse the key already
 *      generated by `services/paymentJournal.ts:79` (`writePaymentJournal`).
 *      This survives app crashes.
 *   2. queueKey — for ops that originated from the offline queue, reuse the
 *      `OfflineOperation.idempotencyKey`. Replays don't generate new keys.
 *   3. Fresh uuidv4() per call.
 *
 * Generate the key BEFORE the first RPC attempt so retries reuse it.
 */
export type IdempotencyOpSignature = {
  /** Operation name, e.g. 'seat_guests'. Used for telemetry only. */
  op: string
  /**
   * For `process_payment`: pass `paymentJournal.idempotencyKey`. Mandatory
   * for that RPC — payment retries MUST reuse the journal's key.
   */
  paymentJournalKey?: string
  /**
   * For replays from `services/offlineSyncService.ts`: pass the existing
   * `OfflineOperation.idempotencyKey`.
   */
  queueKey?: string
}

export function getOrCreateIdempotencyKey (sig: IdempotencyOpSignature): string {
  if (sig.paymentJournalKey) return sig.paymentJournalKey
  if (sig.queueKey) return sig.queueKey
  return uuidv4()
}

/**
 * Helper for Wave 2 client wiring. Returns the RPC name + params to use
 * based on the per-RPC feature flag. When the flag is OFF, returns the
 * v(n) name and original params (zero behavior change). When ON, returns
 * the v(n+1) name and params with a fresh `p_idempotency_key`.
 *
 * Use the optional `keyOverride` to supply a key that must survive across
 * retries (e.g. paymentJournal.idempotencyKey, OfflineOperation.idempotencyKey).
 */
export function withIdempotency<P extends Record<string, any>> (
  rpc: IdempotentRpc,
  v1Name: string,
  v2Name: string,
  params: P,
  keyOverride?: string
): { name: string; params: P & { p_idempotency_key?: string } } {
  if (!isIdempotentEnabled(rpc)) return { name: v1Name, params }
  const p_idempotency_key =
    keyOverride ?? getOrCreateIdempotencyKey({ op: rpc })
  return {
    name: v2Name,
    params: { ...params, p_idempotency_key } as P & { p_idempotency_key: string }
  }
}

/**
 * Composed helper: idempotency-key swap + deadline-wrap in one call.
 *
 * Why combined:
 *   - Idempotency makes retries SAFE (server dedupes via _idempotency_claim).
 *   - Deadline-wrap makes retries TRIGGER (timeout → error → caller's queue).
 * Together they bring Category B RPCs into the connectionQuality state
 * machine on the same terms as the Phase 1 / Option C Category A wraps.
 *
 * On deadline timeout, returns Supabase-shaped `{ data: null, error: {
 * code: 'DEADLINE_EXCEEDED' } }` — caller's existing error path runs.
 *
 * Telemetry: timeouts report to `connectionQuality.reportTimeout(rpc, ms)`,
 * driving fast → degraded → slow transitions and `processQueueNow()` on
 * recovery (via the slow→fast hook in `setupConnectionQuality.ts`).
 */
export async function rpcWithIdempotency<T = unknown> (
  client: SupabaseClient,
  rpc: IdempotentRpc,
  v1Name: string,
  v2Name: string,
  params: Record<string, any>,
  opts?: {
    /** Deadline in ms. Defaults to DEADLINES.hotMutation (2500ms). */
    deadline?: number
    /** Override key for retry-stable operations (queue replays). */
    keyOverride?: string
  }
): Promise<{ data: T | null; error: any }> {
  const { name, params: rpcParams } = withIdempotency(
    rpc, v1Name, v2Name, params, opts?.keyOverride
  )
  const deadlineMs = opts?.deadline ?? DEADLINES.hotMutation
  return runWithDeadline<T>(rpc, deadlineMs, async (signal) => {
    const { data, error } = await client.rpc(name, rpcParams).abortSignal(signal)
    return { data: data as T | null, error }
  })
}
