import CashierStand from "@/components/tables/svg/CashierStand";
import TableSquare2Chair from "@/components/tables/svg/TableSquare2Chair";
import TableSquare4Chair from "@/components/tables/svg/TableSquare4Chair";
import TableSquare8Chair from "@/components/tables/svg/TableSquare8Chair";
import {
  AddOn,
  CartItem,
  Check,
  Discount,
  DrawerSummary,
  EmployeeShift,
  ItemSize,
  MenuItemType,
  ModifierGroup,
  OfflineOrder,
  OnlineOrder,
  Order,
  PaymentTerminal,
  PreviousOrder,
  PrinterDevice,
  PrinterRule,
  ShiftHistoryEntry,
  ShiftStatus,
  TableType,
  TrackedOrder,
  UserProfile,
} from "./types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "45654",
    customerName: "Jake Carter",
    status: "Ready",
    type: "Dine In",
    table: 2,
    time: "2m ago",
  },
  {
    id: "45675",
    customerName: "Emma Brooks",
    status: "Preparing",
    type: "Dine In",
    table: 5,
    time: "2m ago",
  },
  {
    id: "89123",
    customerName: "Liam Smith",
    status: "Preparing",
    type: "Take Away",
    table: 0,
    time: "5m ago",
  },
  {
    id: "45629",
    customerName: "Mason Reed",
    status: "Ready",
    type: "Dine In",
    table: 3,
    time: "8m ago",
  },
  {
    id: "73456",
    customerName: "Olivia Chen",
    status: "Ready",
    type: "Delivery",
    table: 0,
    time: "10m ago",
  },
  {
    id: "94567",
    customerName: "Sophia Roy",
    status: "Preparing",
    type: "Take Away",
    table: 0,
    time: "12m ago",
  },
  {
    id: "12389",
    customerName: "Noah Kim",
    status: "Ready",
    type: "Dine In",
    table: 1,
    time: "15m ago",
  },
  {
    id: "56790",
    customerName: "Ava Jones",
    status: "Ready",
    type: "Delivery",
    table: 0,
    time: "18m ago",
  },
];

export const MENU_IMAGE_MAP = {
  "classic_burger.png": require("../assets/images/classic_burger.png"),
  "bbq_bacon_burger.png": require("../assets/images/bbq_bacon_burger.png"),
  "vegan_wrap.png": require("../assets/images/vegan_wrap.png"),
  "margherita_pizza.png": require("../assets/images/margherita_pizza.png"),
  "chicken_caesar_salad.png": require("../assets/images/chicken_caesar_salad.png"),
  "french_fries.png": require("../assets/images/french_fries.png"),
  "onion_rings.png": require("../assets/images/onion_rings.png"),
  "coke.png": require("../assets/images/coke.png"),
  "sprite.png": require("../assets/images/sprite.png"),
  "chocolate_cake.png": require("../assets/images/chocolate_cake.png"),
  "cheesecake.png": require("../assets/images/cheesecake.png"),
  "pancakes.png": require("../assets/images/pancakes.png"),
  "eggs_benedict.png": require("../assets/images/eggs_benedict.png"),
  // New menu item images
  // "pepperoni_supreme_pizza.png": require("../assets/images/pepperoni_supreme_pizza.png"),
  // "mediterranean_quinoa_bowl.png": require("../assets/images/mediterranean_quinoa_bowl.png"),
  // "club_sandwich.png": require("../assets/images/club_sandwich.png"),
  // "alfredo_pasta.png": require("../assets/images/alfredo_pasta.png"),
  // "buffalo_wings.png": require("../assets/images/buffalo_wings.png"),
  // "loaded_nachos.png": require("../assets/images/loaded_nachos.png"),
  // "tomato_basil_soup.png": require("../assets/images/tomato_basil_soup.png"),
  // "chicken_noodle_soup.png": require("../assets/images/chicken_noodle_soup.png"),
  // "fresh_coffee.png": require("../assets/images/fresh_coffee.png"),
  // "tropical_smoothie.png": require("../assets/images/tropical_smoothie.png"),
  // "orange_juice.png": require("../assets/images/orange_juice.png"),
  // "belgian_waffles.png": require("../assets/images/belgian_waffles.png"),
  // "avocado_toast.png": require("../assets/images/avocado_toast.png"),
  // "tiramisu.png": require("../assets/images/tiramisu.png"),
  // "chocolate_chip_cookies.png": require("../assets/images/chocolate_chip_cookies.png"),
};

const fifteenPercentOff: Discount = {
  id: "promo1",
  label: "15% Off",
  value: 0.15,
  type: "percentage",
};
const tenPercentOff: Discount = {
  id: "promo2",
  label: "10% Off",
  value: 0.1,
  type: "percentage",
};

const standardSizes: ItemSize[] = [
  { id: "size_reg", name: "Regular", priceModifier: 0.0 },
  { id: "size_lg", name: "Large", priceModifier: 2.0 },
];
const burgerAddOns: AddOn[] = [
  { id: "addon_onion", name: "Extra onions", price: 1.0 },
  { id: "addon_cheese", name: "Extra Cheese", price: 1.5 },
  { id: "addon_egg", name: "Extra Fried Egg", price: 2.0 },
];

// --- Custom Add-Ons (Category-Specific) ---
const wrapAddOns: AddOn[] = [
  { id: "wrap1", name: "Extra Avocado", price: 1.0 },
  { id: "wrap2", name: "Gluten-Free Wrap", price: 1.5 },
  { id: "wrap3", name: "Spicy Mayo", price: 0.5 },
];

const pizzaAddOns: AddOn[] = [
  { id: "pizza1", name: "Extra Cheese", price: 1.5 },
  { id: "pizza2", name: "Pepperoni", price: 2.0 },
  { id: "pizza3", name: "Mushrooms", price: 1.0 },
];

const saladAddOns: AddOn[] = [
  { id: "salad1", name: "Grilled Chicken", price: 2.0 },
  { id: "salad2", name: "Parmesan", price: 0.75 },
  { id: "salad3", name: "Croutons", price: 0.5 },
];

const sidesAddOns: AddOn[] = [
  { id: "side1", name: "Garlic Aioli", price: 0.5 },
  { id: "side2", name: "Cheese Sauce", price: 0.75 },
  { id: "side3", name: "Truffle Oil Drizzle", price: 1.0 },
];

const drinksAddOns: AddOn[] = [
  { id: "drink1", name: "Lemon Slice", price: 0.25 },
  { id: "drink2", name: "Extra Ice", price: 0.0 },
  { id: "drink3", name: "Flavor Shot (Vanilla)", price: 0.5 },
];

const dessertAddOns: AddOn[] = [
  { id: "dessert1", name: "Vanilla Ice Cream Scoop", price: 1.5 },
  { id: "dessert2", name: "Chocolate Syrup", price: 0.5 },
  { id: "dessert3", name: "Strawberries", price: 1.0 },
];

const brunchAddOns: AddOn[] = [
  { id: "brunch1", name: "Maple Syrup", price: 0.5 },
  { id: "brunch2", name: "Fresh Berries", price: 1.5 },
  { id: "brunch3", name: "Whipped Cream", price: 0.75 },
];

// --- Additional Add-Ons for New Categories ---
const pastaAddOns: AddOn[] = [
  { id: "pasta1", name: "Extra Parmesan", price: 0.75 },
  { id: "pasta2", name: "Red Pepper Flakes", price: 0.25 },
  { id: "pasta3", name: "Garlic Bread", price: 2.0 },
];

const soupAddOns: AddOn[] = [
  { id: "soup1", name: "Extra Crackers", price: 0.5 },
  { id: "soup2", name: "Side Salad", price: 3.0 },
  { id: "soup3", name: "Extra Bread", price: 1.0 },
];

const sandwichAddOns: AddOn[] = [
  { id: "sandwich1", name: "Extra Mayo", price: 0.25 },
  { id: "sandwich2", name: "Mustard", price: 0.25 },
  { id: "sandwich3", name: "Side Pickles", price: 0.5 },
];

const coffeeAddOns: AddOn[] = [
  { id: "coffee1", name: "Extra Shot", price: 0.75 },
  { id: "coffee2", name: "Whipped Cream", price: 0.5 },
  { id: "coffee3", name: "Extra Hot", price: 0.0 },
];

const smoothieAddOns: AddOn[] = [
  { id: "smoothie1", name: "Protein Powder", price: 1.5 },
  { id: "smoothie2", name: "Extra Fruit", price: 1.0 },
  { id: "smoothie3", name: "Honey", price: 0.5 },
];

const breakfastAddOns: AddOn[] = [
  { id: "breakfast1", name: "Extra Butter", price: 0.25 },
  { id: "breakfast2", name: "Side Bacon", price: 2.0 },
  { id: "breakfast3", name: "Fresh Fruit", price: 1.5 },
];
// --- Additional Add-Ons for Expanded Categories ---
const steakAddOns: AddOn[] = [
  { id: "steak1", name: "Mushroom Sauce", price: 2.0 },
  { id: "steak2", name: "Peppercorn Sauce", price: 2.0 },
  { id: "steak3", name: "Garlic Butter", price: 1.0 },
];

const seafoodAddOns: AddOn[] = [
  { id: "seafood1", name: "Extra Lemon", price: 0.25 },
  { id: "seafood2", name: "Side Rice", price: 2.0 },
  { id: "seafood3", name: "Coleslaw", price: 1.5 },
];

const tacoAddOns: AddOn[] = [
  { id: "taco1", name: "Extra Salsa", price: 0.5 },
  { id: "taco2", name: "Side Chips", price: 1.5 },
  { id: "taco3", name: "Refried Beans", price: 1.0 },
];

const ramenAddOns: AddOn[] = [
  { id: "ramen1", name: "Extra Noodles", price: 2.0 },
  { id: "ramen2", name: "Side Gyoza", price: 3.0 },
  { id: "ramen3", name: "Extra Broth", price: 1.0 },
];

const sushiAddOns: AddOn[] = [
  { id: "sushi1", name: "Extra Ginger", price: 0.25 },
  { id: "sushi2", name: "Soy Sauce", price: 0.0 },
  { id: "sushi3", name: "Side Miso Soup", price: 2.0 },
];

const iceCreamAddOns: AddOn[] = [
  { id: "icecream1", name: "Waffle Cone", price: 1.0 },
  { id: "icecream2", name: "Chocolate Dip", price: 1.5 },
  { id: "icecream3", name: "Extra Hot Fudge", price: 1.0 },
];

const teaAddOns: AddOn[] = [
  { id: "tea1", name: "Honey", price: 0.5 },
  { id: "tea2", name: "Lemon Slice", price: 0.25 },
  { id: "tea3", name: "Extra Hot Water", price: 0.0 },
];

const energyDrinkAddOns: AddOn[] = [
  { id: "energy1", name: "Extra Ice", price: 0.0 },
  { id: "energy2", name: "Energy Shot", price: 2.0 },
  { id: "energy3", name: "Vitamin Boost", price: 1.5 },
];

export const MOCK_MODIFIER_GROUPS: ModifierGroup[] = [
  // Burger Modifiers
  {
    id: "mg_burger_size",
    name: "Burger Size",
    isEnabled: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt_burger_size_single", name: "Single", price: 0 },
      { id: "opt_burger_size_double", name: "Double", price: 2.0 },
    ],
  },
  {
    id: "mg_burger_patty",
    name: "Burger Patty",
    isEnabled: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt_burger_patty_beef", name: "Beef", price: 0 },
      { id: "opt_burger_patty_turkey", name: "Turkey", price: 0.5 },
      { id: "opt_burger_patty_veggie", name: "Veggie", price: 0.5 },
    ],
  },
  {
    id: "mg_burger_cheese",
    name: "Burger Cheese",
    isEnabled: true,
    minSelections: 0,
    maxSelections: 1,
    options: [
      { id: "opt_burger_cheese_cheddar", name: "Cheddar", price: 0.75 },
      { id: "opt_burger_cheese_american", name: "American", price: 0.75 },
      { id: "opt_burger_cheese_swiss", name: "Swiss", price: 0.75 },
      { id: "opt_burger_cheese_none", name: "No Cheese", price: 0 },
    ],
  },
  {
    id: "mg_burger_toppings",
    name: "Burger Toppings",
    isEnabled: true,
    minSelections: 0,
    maxSelections: 3,
    options: [
      { id: "opt_burger_toppings_lettuce", name: "Lettuce", price: 0 },
      { id: "opt_burger_toppings_tomato", name: "Tomato", price: 0 },
      { id: "opt_burger_toppings_onion", name: "Onion", price: 0 },
      { id: "opt_burger_toppings_bacon", name: "Bacon", price: 1.0 },
    ],
  },
  // Pizza Modifiers
  {
    id: "mg_pizza_size",
    name: "Pizza Size",
    isEnabled: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt_pizza_size_small", name: 'Small (10")', price: 0 },
      { id: "opt_pizza_size_medium", name: 'Medium (12")', price: 3.0 },
      { id: "opt_pizza_size_large", name: 'Large (14")', price: 5.0 },
    ],
  },
  {
    id: "mg_pizza_crust",
    name: "Pizza Crust",
    isEnabled: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt_pizza_crust_thin", name: "Thin Crust", price: 0 },
      { id: "opt_pizza_crust_regular", name: "Regular", price: 0 },
      { id: "opt_pizza_crust_thick", name: "Thick Crust", price: 1.0 },
    ],
  },
  {
    id: "mg_pizza_toppings",
    name: "Pizza Toppings",
    isEnabled: true,
    minSelections: 0,
    maxSelections: 5,
    options: [
      { id: "opt_pizza_toppings_pepperoni", name: "Pepperoni", price: 1.5 },
      { id: "opt_pizza_toppings_sausage", name: "Italian Sausage", price: 1.5 },
      { id: "opt_pizza_toppings_mushrooms", name: "Mushrooms", price: 1.5 },
    ],
  },
  // Salad Modifiers
  {
    id: "mg_salad_dressing",
    name: "Salad Dressing",
    isEnabled: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt_salad_dressing_caesar", name: "Caesar", price: 0 },
      { id: "opt_salad_dressing_ranch", name: "Ranch", price: 0 },
      {
        id: "opt_salad_dressing_balsamic",
        name: "Balsamic Vinaigrette",
        price: 0,
      },
    ],
  },
  {
    id: "mg_salad_protein",
    name: "Salad Protein",
    isEnabled: true,
    minSelections: 0,
    maxSelections: 1,
    options: [
      { id: "opt_salad_protein_chicken", name: "Grilled Chicken", price: 3.0 },
      { id: "opt_salad_protein_salmon", name: "Grilled Salmon", price: 5.0 },
      { id: "opt_salad_protein_tofu", name: "Grilled Tofu", price: 2.5 },
    ],
  },
  // Coffee Modifiers
  {
    id: "mg_coffee_size",
    name: "Coffee Size",
    isEnabled: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt_coffee_size_small", name: "Small (8oz)", price: 0 },
      { id: "opt_coffee_size_medium", name: "Medium (12oz)", price: 0.5 },
      { id: "opt_coffee_size_large", name: "Large (16oz)", price: 1.0 },
    ],
  },
  {
    id: "mg_coffee_milk",
    name: "Coffee Milk Options",
    isEnabled: true,
    minSelections: 0,
    maxSelections: 1,
    options: [
      { id: "opt_coffee_milk_whole", name: "Whole Milk", price: 0 },
      { id: "opt_coffee_milk_oat", name: "Oat Milk", price: 0.5 },
      { id: "opt_coffee_milk_almond", name: "Almond Milk", price: 0.5 },
    ],
  },
  // Add more groups as needed from the other arrays...
];

export const MOCK_MENU_ITEMS: MenuItemType[] = [
  // --- Main Course ---
  {
    id: "1",
    name: "Classic Burger",
    description:
      "Features with two juicy chicken patties, melted cheese, crisp lettuce, fresh tomatoes, etc. Perfect for those who crave a hearty, flavorful bite!",
    price: 9.99,
    pricingType: "fixed",
    image: "classic_burger.png",
    color: "#FEE2E2",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    sizes: standardSizes,
    addOns: burgerAddOns,
    modifierGroupIds: [
      "mg_burger_size",
      "mg_burger_patty",
      "mg_burger_cheese",
      "mg_burger_toppings",
    ],
    allergens: ["Gluten", "Dairy"],
    availability: true,
    serialNo: "001",
    stock: 50,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 10:30 AM",
    parLevel: 24,
  },
  {
    id: "2",
    name: "BBQ Bacon Burger",
    description:
      "Smoky BBQ sauce, crispy bacon, and melted cheddar on a juicy patty.",
    price: 12.99,
    pricingType: "fixed",
    image: "bbq_bacon_burger.png",
    color: "#FFEDD5",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: burgerAddOns,
    modifierGroupIds: [
      "mg_burger_size",
      "mg_burger_patty",
      "mg_burger_cheese",
      "mg_burger_toppings",
    ],
    allergens: ["Gluten", "Dairy"],
    availability: true,
    serialNo: "002",
    stock: 45,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 10:35 AM",
    parLevel: 20,
  },
  {
    id: "3",
    name: "Vegan Wrap",
    description:
      "Fresh veggies, hummus, and greens wrapped in a soft tortilla.",
    price: 8.99,
    pricingType: "fixed",
    image: "vegan_wrap.png",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: wrapAddOns,
    availability: true,
    serialNo: "003",
    stock: 30,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 10:40 AM",
    parLevel: 15,
  },
  {
    id: "4",
    name: "Margherita Pizza",
    description:
      "Classic tomato, fresh mozzarella, and basil on a crispy crust.",
    price: 14.5,
    pricingType: "fixed",
    image: "margherita_pizza.png",
    color: "#FEF9C3",
    meal: ["Dinner", "Specials"],
    category: "Main Course",
    addOns: pizzaAddOns,
    availability: true,
    serialNo: "004",
    stock: 25,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 10:45 AM",
    parLevel: 12,
  },
  // --- Appetizers ---
  {
    id: "5",
    name: "Chicken Caesar Salad",
    description:
      "Crisp romaine, Caesar dressing, and croutons with shaved parmesan.",
    price: 7.5,
    pricingType: "fixed",
    image: "chicken_caesar_salad.png",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: saladAddOns,
    availability: true,
    serialNo: "005",
    stock: 35,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 10:50 AM",
    parLevel: 18,
  },
  // --- Sides ---
  {
    id: "6",
    name: "French Fries",
    description: "Golden and crispy fries, lightly seasoned.",
    price: 3.99,
    pricingType: "fixed",
    image: "french_fries.png",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner", "Brunch"],
    category: "Sides",
    addOns: sidesAddOns,
    availability: true,
    serialNo: "006",
    stock: 200,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 10:55 AM",
    parLevel: 100,
  },
  {
    id: "7",
    name: "Onion Rings",
    description: "Beer-battered onion rings with a crunchy bite.",
    price: 4.99,
    pricingType: "fixed",
    image: "onion_rings.png",
    color: "#F3E8FF",
    meal: ["Lunch", "Dinner"],
    category: "Sides",
    addOns: sidesAddOns,
    availability: true,
    serialNo: "007",
    stock: 150,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:00 AM",
    parLevel: 75,
  },
  // --- Drinks ---
  {
    id: "8",
    name: "Coca-Cola",
    description: "Refreshing classic cola served chilled.",
    price: 1.99,
    pricingType: "fixed",
    image: "coke.png",
    color: "#F3F4F6",
    meal: ["Lunch", "Dinner", "Brunch", "Specials"],
    category: "Drinks",
    addOns: drinksAddOns,
    availability: true,
    serialNo: "008",
    stock: 300,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:05 AM",
    parLevel: 150,
  },
  {
    id: "9",
    name: "Sprite",
    description: "Lemon-lime soda with a crisp, clean taste.",
    price: 1.99,
    pricingType: "fixed",
    image: "sprite.png",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner", "Brunch", "Specials"],
    category: "Drinks",
    addOns: drinksAddOns,
    availability: true,
    serialNo: "009",
    stock: 280,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:10 AM",
    parLevel: 140,
  },
  // --- Desserts ---
  {
    id: "10",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with a gooey molten center.",
    price: 6.99,
    pricingType: "fixed",
    image: "chocolate_cake.png",
    color: "#FEE2E2",
    meal: ["Dinner"],
    category: "Dessert",
    addOns: dessertAddOns,
    availability: true,
    serialNo: "010",
    stock: 40,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:15 AM",
    parLevel: 20,
  },
  {
    id: "11",
    name: "New York Cheesecake",
    description: "Rich and creamy cheesecake on a buttery graham crust.",
    price: 7.25,
    pricingType: "fixed",
    image: "cheesecake.png",
    color: "#FCE7F3",
    meal: ["Dinner"],
    category: "Dessert",
    addOns: dessertAddOns,
    availability: true,
    serialNo: "011",
    stock: 35,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:20 AM",
    parLevel: 18,
  },
  // --- Brunch ---
  {
    id: "12",
    name: "Fluffy Pancakes",
    description: "Stack of light, fluffy pancakes served with butter.",
    price: 8.5,
    pricingType: "fixed",
    image: "pancakes.png",
    color: "#E0E7FF",
    meal: ["Brunch", "Specials"],
    category: "Main Course",
    addOns: brunchAddOns,
    availability: true,
    serialNo: "012",
    stock: 60,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:25 AM",
    parLevel: 30,
  },
  {
    id: "13",
    name: "Eggs Benedict",
    description:
      "Poached eggs, Canadian bacon, and hollandaise on an English muffin.",
    price: 10.5,
    pricingType: "fixed",
    image: "eggs_benedict.png",
    color: "#CFFAFE",
    meal: ["Brunch"],
    category: "Main Course",
    addOns: brunchAddOns,
    availability: true,
    serialNo: "013",
    stock: 45,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:30 AM",
    parLevel: 22,
  },
  // --- Additional Main Course Items ---
  {
    id: "14",
    name: "Pepperoni Supreme Pizza",
    description:
      "Loaded with pepperoni, Italian sausage, mushrooms, bell peppers, and mozzarella on our signature crust.",
    price: 16.99,
    pricingType: "fixed",
    color: "#FEE2E2",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    sizes: standardSizes,
    addOns: pizzaAddOns,
    modifierGroupIds: ["mg_pizza_size", "mg_pizza_crust", "mg_pizza_toppings"],
    allergens: ["Gluten", "Dairy"],
    availability: true,
    serialNo: "014",
    stock: 28,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:35 AM",
    parLevel: 14,
  },
  {
    id: "15",
    name: "Mediterranean Quinoa Bowl",
    description:
      "Nutrient-packed quinoa with roasted vegetables, feta cheese, olives, and lemon-tahini dressing.",
    price: 11.99,
    pricingType: "fixed",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: saladAddOns,
    modifierGroupIds: ["mg_salad_dressing", "mg_salad_protein"],
    allergens: ["Dairy"],
    availability: true,
    serialNo: "015",
    stock: 40,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:40 AM",
    parLevel: 20,
  },
  {
    id: "16",
    name: "Classic Club Sandwich",
    description:
      "Triple-decker with turkey, bacon, lettuce, tomato, and mayo on toasted bread.",
    price: 9.99,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: sandwichAddOns,
    modifierGroupIds: ["mg_sandwich_toppings"],
    allergens: ["Gluten", "Dairy"],
    availability: true,
    serialNo: "016",
    stock: 35,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:45 AM",
    parLevel: 18,
  },
  {
    id: "17",
    name: "Creamy Alfredo Pasta",
    description:
      "Rich and creamy alfredo sauce over perfectly cooked pasta with parmesan cheese.",
    price: 13.99,
    pricingType: "fixed",
    color: "#FFEDD5",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: pastaAddOns,
    modifierGroupIds: ["mg_pasta_sauce", "mg_pasta_toppings"],
    allergens: ["Gluten", "Dairy"],
    availability: true,
    serialNo: "017",
    stock: 42,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:50 AM",
    parLevel: 21,
  },
  // --- Appetizers ---
  {
    id: "18",
    name: "Buffalo Wings",
    description:
      "Crispy chicken wings tossed in our signature buffalo sauce, served with celery and blue cheese.",
    price: 8.99,
    pricingType: "fixed",
    color: "#FFEDD5",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: sidesAddOns,
    allergens: ["Dairy"],
    availability: true,
    serialNo: "018",
    stock: 65,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 11:55 AM",
    parLevel: 32,
  },
  {
    id: "19",
    name: "Loaded Nachos",
    description:
      "Tortilla chips topped with melted cheese, jalapeños, sour cream, and guacamole.",
    price: 7.99,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: sidesAddOns,
    allergens: ["Dairy"],
    availability: true,
    serialNo: "019",
    stock: 55,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:00 PM",
    parLevel: 28,
  },
  // --- Soups (as Appetizers) ---
  {
    id: "20",
    name: "Tomato Basil Soup",
    description:
      "Rich and creamy tomato soup with fresh basil, perfect comfort food.",
    price: 5.99,
    pricingType: "fixed",
    color: "#FEE2E2",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: soupAddOns,
    modifierGroupIds: ["mg_soup_toppings"],
    allergens: ["Dairy"],
    availability: true,
    serialNo: "020",
    stock: 80,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:05 PM",
    parLevel: 40,
  },
  {
    id: "21",
    name: "Chicken Noodle Soup",
    description:
      "Classic comfort soup with tender chicken, egg noodles, and fresh vegetables.",
    price: 6.99,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: soupAddOns,
    modifierGroupIds: ["mg_soup_toppings"],
    allergens: ["Gluten", "Eggs"],
    availability: true,
    serialNo: "021",
    stock: 75,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:10 PM",
    parLevel: 38,
  },
  // --- Drinks ---
  {
    id: "22",
    name: "Fresh Brewed Coffee",
    description:
      "Premium blend of Arabica beans, freshly ground and brewed to perfection.",
    price: 2.99,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner", "Brunch"],
    category: "Drinks",
    addOns: coffeeAddOns,
    modifierGroupIds: ["mg_coffee_size", "mg_coffee_milk"],
    allergens: [],
    availability: true,
    serialNo: "022",
    stock: 500,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:15 PM",
    parLevel: 250,
  },
  {
    id: "23",
    name: "Tropical Smoothie",
    description:
      "Blend of mango, pineapple, banana, and coconut milk for a refreshing treat.",
    price: 6.99,
    pricingType: "fixed",
    color: "#FFEDD5",
    meal: ["Lunch", "Brunch"],
    category: "Drinks",
    addOns: smoothieAddOns,
    allergens: ["Dairy"],
    availability: true,
    serialNo: "023",
    stock: 120,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:20 PM",
    parLevel: 60,
  },
  {
    id: "24",
    name: "Fresh Orange Juice",
    description:
      "Freshly squeezed orange juice, rich in vitamin C and natural sweetness.",
    price: 3.99,
    pricingType: "fixed",
    color: "#FFEDD5",
    meal: ["Brunch"],
    category: "Drinks",
    allergens: [],
    availability: true,
    serialNo: "024",
    stock: 90,
    unit: "Liters",
    status: "Active",
    lastUpdate: "09/10/2025, 12:25 PM",
    parLevel: 45,
  },
  // --- Breakfast Items (as Main Course) ---
  {
    id: "25",
    name: "Belgian Waffles",
    description:
      "Light and fluffy Belgian waffles served with butter and maple syrup.",
    price: 9.99,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Brunch"],
    category: "Main Course",
    addOns: breakfastAddOns,
    allergens: ["Gluten", "Dairy", "Eggs"],
    availability: true,
    serialNo: "025",
    stock: 55,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:30 PM",
    parLevel: 28,
  },
  {
    id: "26",
    name: "Avocado Toast",
    description:
      "Smashed avocado on artisan bread with cherry tomatoes, feta, and balsamic glaze.",
    price: 8.99,
    pricingType: "fixed",
    color: "#DCFCE7",
    meal: ["Brunch"],
    category: "Main Course",
    addOns: breakfastAddOns,
    allergens: ["Gluten", "Dairy"],
    availability: true,
    serialNo: "026",
    stock: 48,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:35 PM",
    parLevel: 24,
  },
  // --- Desserts ---
  {
    id: "27",
    name: "Tiramisu",
    description:
      "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.",
    price: 7.99,
    pricingType: "fixed",
    color: "#F3E8FF",
    meal: ["Dinner"],
    category: "Dessert",
    addOns: dessertAddOns,
    allergens: ["Dairy", "Eggs", "Gluten"],
    availability: true,
    serialNo: "027",
    stock: 38,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:40 PM",
    parLevel: 19,
  },
  {
    id: "28",
    name: "Chocolate Chip Cookies",
    description:
      "Warm, gooey chocolate chip cookies baked fresh daily, served with milk.",
    price: 4.99,
    pricingType: "fixed",
    color: "#FEE2E2",
    meal: ["Lunch", "Dinner"],
    category: "Dessert",
    addOns: dessertAddOns,
    allergens: ["Gluten", "Dairy", "Eggs"],
    availability: true,
    serialNo: "028",
    stock: 100,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:45 PM",
    parLevel: 50,
  },
  // --- Additional Main Course Items (29-40) ---
  {
    id: "29",
    name: "Grilled Ribeye Steak",
    description:
      "Premium ribeye steak grilled to perfection, served with your choice of sides.",
    price: 24.99,
    pricingType: "fixed",
    color: "#F3E8FF",
    meal: ["Dinner"],
    category: "Main Course",
    addOns: steakAddOns,
    modifierGroupIds: ["mg_steak_size", "mg_steak_flavor", "mg_steak_toppings"],
    allergens: [],
    availability: true,
    serialNo: "029",
    stock: 25,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:50 PM",
    parLevel: 12,
  },
  {
    id: "30",
    name: "Grilled Salmon Fillet",
    description:
      "Fresh Atlantic salmon fillet grilled with herbs and lemon, served with seasonal vegetables.",
    price: 18.99,
    pricingType: "fixed",
    color: "#DBEAFE",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: seafoodAddOns,
    modifierGroupIds: [
      "mg_seafood_size",
      "mg_seafood_flavor",
      "mg_seafood_toppings",
    ],
    allergens: ["Fish"],
    availability: true,
    serialNo: "030",
    stock: 32,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 12:55 PM",
    parLevel: 16,
  },
  {
    id: "31",
    name: "Fish Tacos",
    description:
      "Three soft tacos filled with grilled fish, cabbage slaw, and chipotle aioli.",
    price: 12.99,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: tacoAddOns,
    modifierGroupIds: ["mg_taco_size", "mg_taco_flavor", "mg_taco_toppings"],
    allergens: ["Fish", "Gluten"],
    availability: true,
    serialNo: "031",
    stock: 45,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:00 PM",
    parLevel: 22,
  },
  {
    id: "32",
    name: "Chicken Tacos",
    description:
      "Three soft tacos with grilled chicken, pico de gallo, and avocado crema.",
    price: 11.99,
    pricingType: "fixed",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: tacoAddOns,
    modifierGroupIds: ["mg_taco_size", "mg_taco_flavor", "mg_taco_toppings"],
    allergens: ["Gluten"],
    availability: true,
    serialNo: "032",
    stock: 50,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:05 PM",
    parLevel: 25,
  },
  {
    id: "33",
    name: "Tonkotsu Ramen",
    description:
      "Rich pork bone broth with chashu pork, soft-boiled egg, and fresh noodles.",
    price: 14.99,
    pricingType: "fixed",
    color: "#FFEDD5",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: ramenAddOns,
    modifierGroupIds: ["mg_ramen_size", "mg_ramen_flavor", "mg_ramen_toppings"],
    allergens: ["Gluten", "Eggs", "Soy"],
    availability: true,
    serialNo: "033",
    stock: 38,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:10 PM",
    parLevel: 19,
  },
  {
    id: "34",
    name: "Miso Ramen",
    description:
      "Savory miso broth with tofu, corn, and bamboo shoots over fresh noodles.",
    price: 13.99,
    pricingType: "fixed",
    color: "#DBEAFE",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: ramenAddOns,
    modifierGroupIds: ["mg_ramen_size", "mg_ramen_flavor", "mg_ramen_toppings"],
    allergens: ["Gluten", "Soy"],
    availability: true,
    serialNo: "034",
    stock: 42,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:15 PM",
    parLevel: 21,
  },
  {
    id: "35",
    name: "California Roll",
    description:
      "Crab, avocado, and cucumber roll topped with sesame seeds and served with wasabi.",
    price: 8.99,
    pricingType: "fixed",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: sushiAddOns,
    modifierGroupIds: ["mg_sushi_size", "mg_sushi_flavor", "mg_sushi_toppings"],
    allergens: ["Fish", "Soy"],
    availability: true,
    serialNo: "035",
    stock: 60,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:20 PM",
    parLevel: 30,
  },
  {
    id: "36",
    name: "Spicy Tuna Roll",
    description:
      "Fresh tuna mixed with spicy mayo, wrapped in seaweed and rice.",
    price: 9.99,
    pricingType: "fixed",
    color: "#FEE2E2",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: sushiAddOns,
    modifierGroupIds: ["mg_sushi_size", "mg_sushi_flavor", "mg_sushi_toppings"],
    allergens: ["Fish", "Soy"],
    availability: true,
    serialNo: "036",
    stock: 55,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:25 PM",
    parLevel: 28,
  },
  {
    id: "37",
    name: "Chicken Teriyaki Bowl",
    description:
      "Grilled chicken glazed with teriyaki sauce over steamed rice with vegetables.",
    price: 13.99,
    pricingType: "fixed",
    color: "#FFEDD5",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: pastaAddOns,
    allergens: ["Soy"],
    availability: true,
    serialNo: "037",
    stock: 48,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:30 PM",
    parLevel: 24,
  },
  {
    id: "38",
    name: "Beef Stir Fry",
    description:
      "Tender beef strips with mixed vegetables in a savory sauce over rice.",
    price: 15.99,
    pricingType: "fixed",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: pastaAddOns,
    allergens: ["Soy"],
    availability: true,
    serialNo: "038",
    stock: 40,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:35 PM",
    parLevel: 20,
  },
  {
    id: "39",
    name: "Vegetarian Buddha Bowl",
    description:
      "Quinoa, roasted vegetables, chickpeas, and tahini dressing in a nourishing bowl.",
    price: 12.99,
    pricingType: "fixed",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: saladAddOns,
    modifierGroupIds: ["mg_salad_dressing", "mg_salad_protein"],
    allergens: ["Sesame"],
    availability: true,
    serialNo: "039",
    stock: 52,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:40 PM",
    parLevel: 26,
  },
  {
    id: "40",
    name: "BBQ Pulled Pork Sandwich",
    description:
      "Slow-cooked pulled pork with tangy BBQ sauce on a brioche bun with coleslaw.",
    price: 11.99,
    pricingType: "fixed",
    color: "#FFEDD5",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    addOns: sandwichAddOns,
    modifierGroupIds: ["mg_sandwich_toppings"],
    allergens: ["Gluten"],
    availability: true,
    serialNo: "040",
    stock: 44,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:45 PM",
    parLevel: 22,
  },
  // --- Additional Appetizers (41-45) ---
  {
    id: "41",
    name: "Mozzarella Sticks",
    description: "Crispy breaded mozzarella sticks served with marinara sauce.",
    price: 6.99,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: sidesAddOns,
    allergens: ["Gluten", "Dairy"],
    availability: true,
    serialNo: "041",
    stock: 70,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:50 PM",
    parLevel: 35,
  },
  {
    id: "42",
    name: "Spinach Artichoke Dip",
    description: "Creamy spinach and artichoke dip served with tortilla chips.",
    price: 7.99,
    pricingType: "fixed",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: sidesAddOns,
    allergens: ["Dairy"],
    availability: true,
    serialNo: "042",
    stock: 65,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 1:55 PM",
    parLevel: 32,
  },
  {
    id: "43",
    name: "Chicken Quesadilla",
    description:
      "Grilled chicken, cheese, and peppers in a crispy tortilla with sour cream.",
    price: 8.99,
    pricingType: "fixed",
    color: "#FFEDD5",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: sidesAddOns,
    allergens: ["Gluten", "Dairy"],
    availability: true,
    serialNo: "043",
    stock: 58,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 2:00 PM",
    parLevel: 29,
  },
  {
    id: "44",
    name: "Calamari Rings",
    description:
      "Crispy fried calamari rings served with marinara and lemon aioli.",
    price: 9.99,
    pricingType: "fixed",
    color: "#DBEAFE",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: sidesAddOns,
    allergens: ["Seafood", "Gluten"],
    availability: true,
    serialNo: "044",
    stock: 45,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 2:05 PM",
    parLevel: 22,
  },
  {
    id: "45",
    name: "Stuffed Mushrooms",
    description:
      "Button mushrooms stuffed with herbed cream cheese and breadcrumbs.",
    price: 6.99,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
    addOns: sidesAddOns,
    allergens: ["Dairy", "Gluten"],
    availability: true,
    serialNo: "045",
    stock: 62,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 2:10 PM",
    parLevel: 31,
  },
  // --- Additional Sides (46-47) ---
  {
    id: "46",
    name: "Sweet Potato Fries",
    description: "Crispy sweet potato fries seasoned with sea salt and herbs.",
    price: 4.99,
    pricingType: "fixed",
    color: "#FFEDD5",
    meal: ["Lunch", "Dinner"],
    category: "Sides",
    addOns: sidesAddOns,
    allergens: [],
    availability: true,
    serialNo: "046",
    stock: 180,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 2:15 PM",
    parLevel: 90,
  },
  {
    id: "47",
    name: "Mac and Cheese",
    description:
      "Creamy three-cheese macaroni and cheese with a crispy breadcrumb topping.",
    price: 5.99,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner"],
    category: "Sides",
    addOns: sidesAddOns,
    allergens: ["Gluten", "Dairy"],
    availability: true,
    serialNo: "047",
    stock: 160,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 2:20 PM",
    parLevel: 80,
  },
  // --- Additional Drinks (48-50) ---
  {
    id: "48",
    name: "Green Tea",
    description:
      "Premium green tea leaves steeped to perfection, served hot or iced.",
    price: 2.99,
    pricingType: "fixed",
    color: "#DCFCE7",
    meal: ["Lunch", "Dinner", "Brunch"],
    category: "Drinks",
    addOns: teaAddOns,
    allergens: [],
    availability: true,
    serialNo: "048",
    stock: 400,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 2:25 PM",
    parLevel: 200,
  },
  {
    id: "49",
    name: "Energy Drink",
    description:
      "Refreshing energy drink with natural caffeine and B-vitamins.",
    price: 3.99,
    pricingType: "fixed",
    color: "#FEE2E2",
    meal: ["Lunch", "Dinner"],
    category: "Drinks",
    addOns: energyDrinkAddOns,
    allergens: [],
    availability: true,
    serialNo: "049",
    stock: 220,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 2:30 PM",
    parLevel: 110,
  },
  {
    id: "50",
    name: "Iced Tea",
    description: "Freshly brewed black tea served over ice with lemon.",
    price: 2.49,
    pricingType: "fixed",
    color: "#FEF9C3",
    meal: ["Lunch", "Dinner", "Brunch"],
    category: "Drinks",
    addOns: teaAddOns,
    allergens: [],
    availability: true,
    serialNo: "050",
    stock: 350,
    unit: "PCs",
    status: "Active",
    lastUpdate: "09/10/2025, 2:35 PM",
    parLevel: 175,
  },
];

export const MOCK_TABLES: TableType[] = [
  // Top Row (Circles)
  {
    id: "cashier-1",
    name: "",
    status: "Not in Service", // Status doesn't really apply, but we need one
    capacity: 0,
    component: CashierStand,
    x: 50,
    y: 300,
    rotation: 0,
    type: "static-object", // Set its type
  },
  {
    id: "8",
    name: "T-8",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 40,
    y: 40,
    rotation: 0,
    type: "table",
  },
  {
    id: "7",
    name: "T-7",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 160,
    y: 40,
    rotation: 0,
    type: "table",
  },
  {
    id: "6",
    name: "T-6",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 280,
    y: 40,
    rotation: 0,
    type: "table",
  },
  {
    id: "5",
    name: "T-5",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 400,
    y: 40,
    rotation: 0,

    type: "table",
  },
  {
    id: "1",
    name: "T-1",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 600,
    y: 40,
    rotation: 0,
    type: "table",
  },
  {
    id: "2",
    name: "T-2",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 720,
    y: 40,
    rotation: 0,
    type: "table",
  },
  // Second Row
  {
    id: "4",
    name: "T-4",
    status: "Available",
    capacity: 4,
    component: TableSquare4Chair,
    x: 600,
    y: 150,
    rotation: 0,
    type: "table",
  },
  {
    id: "3",
    name: "T-3",
    status: "Needs Cleaning",
    capacity: 4,
    component: TableSquare4Chair,
    x: 720,
    y: 150,
    rotation: 0,
    type: "table",
  },
  // Middle Rows (Squares)
  {
    id: "10",
    name: "T-10",
    status: "Needs Cleaning",
    capacity: 4,
    component: TableSquare4Chair,
    x: 200,
    y: 250,
    rotation: 0,
    type: "table",
  },
  {
    id: "9",
    name: "T-9",
    status: "Available",
    capacity: 4,
    component: TableSquare4Chair,
    x: 350,
    y: 250,
    rotation: 0,
    type: "table",
  },
  {
    id: "11",
    name: "T-11",
    status: "Available",
    capacity: 4,
    component: TableSquare4Chair,
    x: 200,
    y: 350,
    rotation: 0,
    type: "table",
  },
  {
    id: "12",
    name: "T-12",
    status: "Available",
    capacity: 4,
    component: TableSquare4Chair,
    x: 350,
    y: 350,
    rotation: 0,
    type: "table",
  },
  {
    id: "13",
    name: "T-13",
    status: "Available",
    capacity: 8,
    component: TableSquare8Chair,
    x: 660,
    y: 280,
    rotation: 0,
    type: "table",
  },
  {
    id: "14",
    name: "T-14",
    status: "Needs Cleaning",
    capacity: 8,
    component: TableSquare8Chair,
    x: 660,
    y: 380,
    rotation: 0,
    type: "table",
  },
  {
    id: "15",
    name: "T-15",
    status: "Available",
    capacity: 8,
    component: TableSquare8Chair,
    x: 660,
    y: 480,
    rotation: 0,
    type: "table",
  },
  {
    id: "21",
    name: "T-21",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 200,
    y: 600,
    rotation: 0,
    type: "table",
  },
  {
    id: "20",
    name: "T-20",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 320,
    y: 600,
    rotation: 0,
    type: "table",
  },
  {
    id: "19",
    name: "T-19",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 440,
    y: 600,
    rotation: 0,
    type: "table",
  },
  {
    id: "18",
    name: "T-18",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 560,
    y: 600,
    rotation: 0,
    type: "table",
  },
  {
    id: "17",
    name: "T-17",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 680,
    y: 600,
    rotation: 0,
    type: "table",
  },
  {
    id: "16",
    name: "T-16",
    status: "Available",
    capacity: 2,
    component: TableSquare2Chair,
    x: 800,
    y: 600,
    rotation: 0,
    type: "table",
  },
];

export const PARTNER_LOGO_MAP = {
  "Door Dash": require("@/assets/images/doordash.png"),
  grubhub: require("@/assets/images/grubhub.png"),
  "Uber-Eats": require("@/assets/images/uber-eats.png"),
  "Food Panda": require("@/assets/images/food-panda.png"),
};

const sampleOrderItems: CartItem[] = [
  {
    id: "burger_1",
    menuItemId: "1",
    name: "Double Cheeseburger",
    quantity: 1,
    originalPrice: 7.25,
    price: 13.25,
    customizations: {
      size: { id: "size_lg", name: "Large", priceModifier: 2.0 },
      addOns: [
        { id: "addon_onion", name: "Extra onions", price: 1.0 },
        { id: "addon_cheese", name: "Extra Cheese", price: 1.5 },
        { id: "addon_egg", name: "Extra Fried Egg", price: 1.5 },
      ],
      notes: "Make the cheese more melted",
    },
    image: "classic_burger.png",
  },
  {
    id: "burger_2",
    menuItemId: "1",
    name: "Double Cheeseburger",
    quantity: 1,
    originalPrice: 7.25, // Assuming originalPrice is the base price
    price: 7.25, // Assuming price is the final price after customizations
    customizations: {
      size: { id: "size_reg", name: "Regular", priceModifier: 0 },
    },
    image: "classic_burger.png",
  },
  {
    id: "coke_1",
    menuItemId: "8",
    name: "Coca-Cola",
    quantity: 1,
    originalPrice: 1.99, // Assuming originalPrice is the base price
    price: 1.99, // Assuming price is the final price after customizations
    customizations: {},
    image: "coke.png",
  },
];

export const MOCK_ONLINE_ORDERS: OnlineOrder[] = [
  // Add a variety of orders with different statuses and partners
  {
    id: "#45654",
    status: "New Orders",
    deliveryPartner: "Door Dash",
    customerName: "John Jones",
    total: 520,
    itemCount: 10,
    timestamp: "02/03/25, 05:36 PM",
    customerDetails: {
      id: "#54568",
      phone: "+560934856",
      email: "john@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45655",
    status: "New Orders",
    deliveryPartner: "Uber-Eats",
    customerName: "Jane Smith",
    total: 350,
    itemCount: 5,
    timestamp: "02/03/25, 05:38 PM",
    customerDetails: {
      id: "#54569",
      phone: "+123456789",
      email: "jane@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45656",
    status: "Confirmed/In-Process",
    deliveryPartner: "Food Panda",
    customerName: "Alex Ray",
    total: 410,
    itemCount: 8,
    timestamp: "02/03/25, 05:30 PM",
    customerDetails: {
      id: "#54570",
      phone: "+987654321",
      email: "alex@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45657",
    status: "Confirmed/In-Process",
    deliveryPartner: "grubhub",
    customerName: "Emily Clark",
    total: 600,
    itemCount: 12,
    timestamp: "02/03/25, 05:25 PM",
    customerDetails: {
      id: "#54571",
      phone: "+555555555",
      email: "emily@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45658",
    status: "Ready to Dispatch",
    deliveryPartner: "Uber-Eats",
    customerName: "Michael Bee",
    total: 220,
    itemCount: 3,
    timestamp: "02/03/25, 05:20 PM",
    customerDetails: {
      id: "#54572",
      phone: "+444444444",
      email: "michael@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45659",
    status: "Dispatched",
    deliveryPartner: "Food Panda",
    customerName: "Sarah Day",
    total: 750,
    itemCount: 15,
    timestamp: "02/03/25, 05:15 PM",
    customerDetails: {
      id: "#54573",
      phone: "+666666666",
      email: "sarah@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
];

export const MOCK_PREVIOUS_ORDERS: PreviousOrder[] = [
  {
    serialNo: "001",
    orderDate: "Oct 16, 2024",
    orderTime: "09:31 AM",
    orderId: "#2010E10",
    paymentStatus: "In Progress",
    customer: "John Doe",
    server: "Jake Carter",
    itemCount: 5,
    type: "Dine In",
    total: 34.5,
    items: sampleOrderItems,
  },
  {
    serialNo: "002",
    orderDate: "Oct 16, 2024",
    orderTime: "09:35 AM",
    orderId: "#2010E11",
    paymentStatus: "Paid",
    customer: "Jane Smith",
    server: "Jessica",
    itemCount: 3,
    type: "Take Away",
    total: 22.75,
    items: [],
  },
  {
    serialNo: "003",
    orderDate: "Oct 16, 2024",
    orderTime: "09:40 AM",
    orderId: "#2010E12",
    paymentStatus: "Paid",
    customer: "Alex Johnson",
    server: "Jake Carter",
    itemCount: 8,
    type: "Delivery",
    total: 105.25,
    items: sampleOrderItems,
  },
  {
    serialNo: "004",
    orderDate: "Oct 15, 2024",
    orderTime: "08:15 PM",
    orderId: "#2009E95",
    paymentStatus: "Refunded",
    customer: "Sarah Wilson",
    server: "Jessica",
    itemCount: 2,
    type: "Dine In",
    total: 15.0,
    items: [],
  },
  // Add 5-10 more mock orders to make the list feel full
];

export const MOCK_USER_PROFILE: UserProfile = {
  id: "#54568",
  employeeId: "JS002T",
  fullName: "Tom Hardy",
  dob: "04/09/1996",
  gender: "Male",
  country: "USA",
  address: "New York, USA",
  email: "tom@gmail.com",
  phone: "+8037247534858347",
  pin: "498843",
  profileImageUrl: "tom_hardy.jpg",
};

export const MOCK_SHIFT_STATUS: ShiftStatus = {
  status: "Clocked In",
  duration: "5 h 24 m",
  clockInTime: "08:01 AM",
};

export const MOCK_SHIFT_HISTORY: ShiftHistoryEntry[] = Array.from(
  { length: 7 },
  (_, i) => ({
    id: i.toString(),
    date: "02/03/2025",
    clockIn: "10:30 AM",
    breakInitiated: "12:30 PM",
    breakEnded: "01:30 PM",
    clockOut: "06:30 PM",
    duration: "8h 11m",
    role: "Cashier",
  })
);

export const MOCK_PRINTERS: PrinterDevice[] = [
  {
    id: "1",
    name: "Receipt Printer",
    isEnabled: true,
    status: "Connected",
    connectionType: "Wi-Fi",
    ipAddress: "192.168.1.101",
  },
  {
    id: "2",
    name: "Kitchen Printer",
    isEnabled: true,
    status: "Disconnected",
    connectionType: "Wi-Fi",
    ipAddress: "192.168.1.102",
  },
  {
    id: "3",
    name: "Bar Printer",
    isEnabled: false,
    status: "Disconnected",
    connectionType: "Bluetooth",
  },
];

export const MOCK_CATEGORIES = [
  { label: "Food", value: "Food" },
  { label: "Drinks", value: "Drinks" },
  { label: "Desserts", value: "Desserts" },
  { label: "Appetizers", value: "Appetizers" },
];

export const MOCK_PRINTER_RULES: PrinterRule[] = [
  {
    id: "rule1",
    isEnabled: true,
    category: "Food",
    printerId: MOCK_PRINTERS[0].id,
  },
  {
    id: "rule2",
    isEnabled: false,
    category: "Drinks",
    printerId: MOCK_PRINTERS[2].id,
  },
  {
    id: "rule3",
    isEnabled: false,
    category: "Desserts",
    printerId: MOCK_PRINTERS[1].id,
  },
];

export const MOCK_TERMINALS: PaymentTerminal[] = [
  {
    id: "TRM00123",
    name: "Terminal A-123",
    isEnabled: true,
    status: "Connected",
    batteryLevel: 85,
  },
  {
    id: "TRM00124",
    name: "Terminal B-124",
    isEnabled: true,
    status: "Disconnected",
    batteryLevel: 62,
  },
  {
    id: "TRM00234",
    name: "Terminal D-234",
    isEnabled: false,
    status: "Disconnected",
    batteryLevel: 45,
  },
];

export const MOCK_FOUND_TERMINALS = [
  { id: "Epson-TM", name: "Epson TM-m30II-NT" },
  { id: "PIXMA-E3470", name: "PIXMA E3470" },
  { id: "HP-9025", name: "HP OfficeJet Pro 9025" },
  { id: "Canon-TR4520", name: "Canon PIXMA TR4520" },
  { id: "Brother-HL", name: "Brother HL-L2390DW" },
];

export const MOCK_OFFLINE_ORDERS: OfflineOrder[] = Array(8).fill({
  serialNo: "001",
  orderDate: "Oct 16, 2024",
  orderTime: "09:31 AM",
  orderId: "#2010E10",
  server: "Jake Carter",
  total: 34.5,
});

export const salesData = [
  { hour: 6, today: 180, yesterday: 320 },
  { hour: 8, today: 250, yesterday: 410 },
  { hour: 10, today: 310, yesterday: 240 },
  { hour: 12, today: 190, yesterday: 445 },
  { hour: 14, today: 360, yesterday: 330 },
  { hour: 16, today: 420, yesterday: 290 },
  { hour: 18, today: 320, yesterday: 500 },
  { hour: 20, today: 380, yesterday: 240 },
];

// Mock data for the "Open vs Closed Checks" donut chart
export const checksData = [
  { x: "Open", y: 22.19 },
  { x: "Closed", y: 77.81 },
];

// Mock data for the "Check Status Overview" donut chart
export const checkStatusData = [
  { x: "Completed", y: 56.2 },
  { x: "Pending", y: 34.5 },
  { x: "In Progress", y: 9.3 },
];

// Mock data for the "Top Selling Items" bar chart
export const topItemsData = [
  { name: "Crispy Cheese Burger", quantity: 18 },
  { name: "Chicken Alfredo Pasta", quantity: 13 },
  { name: "Spicy Chicken Burger", quantity: 10 },
  { name: "Beef Shawarma Wrap", quantity: 9 },
  { name: "BBQ Chicken Wings", quantity: 7 },
];

export const MOCK_TRACKED_ORDERS: TrackedOrder[] = [
  {
    id: "1",
    customerName: "John Jones",
    status: "On kitchen Hand",
    type: "Dine In",
    table: 2,
    timestamp: "09:00 AM",
    totalItems: 5,
    items: [
      { name: "Cheese pizza", quantity: 1 },
      { name: "Coffee", quantity: 1 },
      { name: "Cheese pizza", quantity: 1 },
      { name: "Cheese pizza", quantity: 1 },
      { name: "Fries", quantity: 1 },
    ],
  },
  {
    id: "2",
    customerName: "Emily Smith",
    status: "Preparing",
    type: "Takeout",
    table: 0,
    timestamp: "09:02 AM",
    totalItems: 3,
    items: [
      { name: "Vegan Wrap", quantity: 1 },
      { name: "Salad", quantity: 1 },
      { name: "Water", quantity: 1 },
    ],
  },
  {
    id: "3",
    customerName: "Alex Ray",
    status: "On kitchen Hand",
    type: "Dine In",
    table: 5,
    timestamp: "09:05 AM",
    totalItems: 2,
    items: [
      { name: "BBQ Bacon Burger", quantity: 1 },
      { name: "Coke", quantity: 1 },
    ],
  },
  {
    id: "4",
    customerName: "Sarah Day",
    status: "Ready",
    type: "Delivery",
    table: 0,
    timestamp: "09:08 AM",
    totalItems: 6,
    items: [
      { name: "Margherita Pizza", quantity: 2 },
      { name: "Garlic Bread", quantity: 2 },
      { name: "Sprite", quantity: 2 },
    ],
  },
  {
    id: "5",
    customerName: "Michael Bee",
    status: "On kitchen Hand",
    type: "Dine In",
    table: 8,
    timestamp: "09:10 AM",
    totalItems: 4,
    items: [
      { name: "Pancakes", quantity: 1 },
      { name: "Orange Juice", quantity: 1 },
      { name: "Coffee", quantity: 2 },
    ],
  },
];

export const MOCK_CHECKS: Check[] = [
  {
    serialNo: "001",
    checkNo: "27891",
    payee: "John Doe",
    amount: 34.5,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
    status: "Pending",
    items: [
      { name: "Item 1", price: 25.0 },
      { name: "Item 2", price: 20.0 },
    ],
    subtotal: 45.0,
    tax: 5.0,
    tips: 5.0,
    total: 55.0,
  },
  {
    serialNo: "002",
    checkNo: "45103",
    payee: "Jane Smith",
    amount: 34.5,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
    status: "Cleared",
    items: [],
    subtotal: 0,
    tax: 0,
    tips: 0,
    total: 0,
  },
  {
    serialNo: "003",
    checkNo: "88784",
    payee: "John Hart",
    amount: 34.5,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
    status: "Cleared",
    items: [],
    subtotal: 0,
    tax: 0,
    tips: 0,
    total: 0,
  },
  {
    serialNo: "004",
    checkNo: "12095",
    payee: "Peter Jones",
    amount: 34.5,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
    status: "Voided",
    items: [],
    subtotal: 0,
    tax: 0,
    tips: 0,
    total: 0,
  },
  {
    serialNo: "005",
    checkNo: "63487",
    payee: "Sarah Davis",
    amount: 34.5,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
    status: "Cleared",
    items: [],
    subtotal: 0,
    tax: 0,
    tips: 0,
    total: 0,
  },
  // Add more mock checks to fill the list
];

export const MOCK_DRAWER_SUMMARIES: DrawerSummary[] = [
  {
    id: "1",
    status: "Closed",
    cashier: "Jessica Turner",
    drawerName: "Main Counter",
    startingCash: 150.0,
    expectedCash: 550.75,
    actualCash: 550.75,
    difference: 0.0,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
  },
  {
    id: "2",
    status: "Closed",
    cashier: "Jessica Turner",
    drawerName: "Host Stand",
    startingCash: 150.0,
    expectedCash: 550.75,
    actualCash: 550.75,
    difference: 0.0,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
  },
  {
    id: "3",
    status: "Open",
    cashier: "Jessica Turner",
    drawerName: "Manager's Drawer",
    startingCash: 200.0,
    expectedCash: 412.5,
    actualCash: null,
    difference: null,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
  },
  {
    id: "4",
    status: "Closed",
    cashier: "Jessica Turner",
    drawerName: "Bar",
    startingCash: 150.0,
    expectedCash: 550.75,
    actualCash: 550.75,
    difference: 0.0,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
  },
  {
    id: "5",
    status: "Closed",
    cashier: "Jessica Turner",
    drawerName: "Service Station 1",
    startingCash: 150.0,
    expectedCash: 550.75,
    actualCash: 550.75,
    difference: 0.0,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
  },
  {
    id: "6",
    status: "Closed",
    cashier: "Jessica Turner",
    drawerName: "Service Station 2",
    startingCash: 150.0,
    expectedCash: 550.75,
    actualCash: 550.75,
    difference: 0.0,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
  },
  {
    id: "7",
    status: "Closed",
    cashier: "Jessica Turner",
    drawerName: "Patio",
    startingCash: 150.0,
    expectedCash: 550.75,
    actualCash: 550.75,
    difference: 0.0,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
  },
  {
    id: "8",
    status: "Cleared",
    cashier: "Jessica Turner",
    drawerName: "Drawer 1",
    startingCash: 34.5,
    expectedCash: 34.5,
    actualCash: 34.5,
    difference: 0.0,
    dateIssued: "Oct 16, 2024",
    timeIssued: "09:31 AM",
  },
];

export const MOCK_EMPLOYEE_SHIFTS: EmployeeShift[] = [
  {
    id: "1",
    name: "Ethan Brooks",
    jobTitle: "Manager",
    clockInStatus: "Clocked In",
    clockOutStatus: "Clocked Out",
    clockInTime: "10:00 AM",
    clockOutTime: "10:00 AM",
    totalHours: "7 hours, 5 minutes",
    profile: {
      id: "#4856",
      dob: "04/09/1996",
      role: "Manager",
      gender: "Male",
      country: "USA",
      address: "New York, USA",
    },
  },
  {
    id: "2",
    name: "Ava Simmons",
    jobTitle: "Cashier",
    clockInStatus: "Clocked In",
    clockOutStatus: "N/A",
    clockInTime: "9:00 AM",
    clockOutTime: "N/A",
    totalHours: "N/A",
    profile: {
      id: "#4857",
      dob: "...",
      role: "Cashier",
      gender: "Female",
      country: "USA",
      address: "...",
    },
  },
  {
    id: "3",
    name: "Olivia Carter",
    jobTitle: "Cashier",
    clockInStatus: "Clocked In",
    clockOutStatus: "N/A",
    clockInTime: "9:00 AM",
    clockOutTime: "N/A",
    totalHours: "N/A",
    profile: {
      id: "#4858",
      dob: "...",
      role: "Cashier",
      gender: "Female",
      country: "USA",
      address: "...",
    },
  },
  {
    id: "4",
    name: "Sophia Bell",
    jobTitle: "Cashier",
    clockInStatus: "Clocked In",
    clockOutStatus: "N/A",
    clockInTime: "9:00 AM",
    clockOutTime: "N/A",
    totalHours: "N/A",
    profile: {
      id: "#4859",
      dob: "...",
      role: "Cashier",
      gender: "Female",
      country: "USA",
      address: "...",
    },
  },
  {
    id: "5",
    name: "Mason Hall",
    jobTitle: "Cashier",
    clockInStatus: "Clocked In",
    clockOutStatus: "Clocked Out",
    clockInTime: "9:00 AM",
    clockOutTime: "10:00 AM",
    totalHours: "7 hours, 5 minutes",
    profile: {
      id: "#4860",
      dob: "...",
      role: "Cashier",
      gender: "Male",
      country: "USA",
      address: "...",
    },
  },
  // ... add more employees to fill the list
];
