import { CartItem } from "@/stores/useCartStore";
import {
  AddOn,
  Discount,
  InventoryItem,
  ItemSize,
  MenuItemType,
  OfflineOrder,
  OnlineOrder,
  Order,
  PaymentTerminal,
  PreviousOrder,
  PrinterDevice,
  PrinterRule,
  ShiftHistoryEntry,
  ShiftStatus,
  TableType,
  UserProfile,
} from "./types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "45654",
    customerName: "Jake Carter",
    status: "Ready",
    type: "Dine In",
    table: 2,
    time: "2m ago",
  },
  {
    id: "45675",
    customerName: "Emma Brooks",
    status: "Preparing",
    type: "Dine In",
    table: 5,
    time: "2m ago",
  },
  {
    id: "89123",
    customerName: "Liam Smith",
    status: "Preparing",
    type: "Take Away",
    table: 0,
    time: "5m ago",
  },
  {
    id: "45629",
    customerName: "Mason Reed",
    status: "Ready",
    type: "Dine In",
    table: 3,
    time: "8m ago",
  },
  {
    id: "73456",
    customerName: "Olivia Chen",
    status: "Ready",
    type: "Delivery",
    table: 0,
    time: "10m ago",
  },
  {
    id: "94567",
    customerName: "Sophia Roy",
    status: "Preparing",
    type: "Take Away",
    table: 0,
    time: "12m ago",
  },
  {
    id: "12389",
    customerName: "Noah Kim",
    status: "Ready",
    type: "Dine In",
    table: 1,
    time: "15m ago",
  },
  {
    id: "56790",
    customerName: "Ava Jones",
    status: "Ready",
    type: "Delivery",
    table: 0,
    time: "18m ago",
  },
];

export const MENU_IMAGE_MAP = {
  "classic_burger.png": require("../assets/images/classic_burger.png"),
  "bbq_bacon_burger.png": require("../assets/images/bbq_bacon_burger.png"),
  "vegan_wrap.png": require("../assets/images/vegan_wrap.png"),
  "margherita_pizza.png": require("../assets/images/margherita_pizza.png"),
  "chicken_caesar_salad.png": require("../assets/images/chicken_caesar_salad.png"),
  "french_fries.png": require("../assets/images/french_fries.png"),
  "onion_rings.png": require("../assets/images/onion_rings.png"),
  "coke.png": require("../assets/images/coke.png"),
  "sprite.png": require("../assets/images/sprite.png"),
  "chocolate_cake.png": require("../assets/images/chocolate_cake.png"),
  "cheesecake.png": require("../assets/images/cheesecake.png"),
  "pancakes.png": require("../assets/images/pancakes.png"),
  "eggs_benedict.png": require("../assets/images/eggs_benedict.png"),
};

const fifteenPercentOff: Discount = {
  id: "promo1",
  label: "15% Off",
  value: 0.15,
  type: "percentage",
};
const tenPercentOff: Discount = {
  id: "promo2",
  label: "10% Off",
  value: 0.1,
  type: "percentage",
};

const standardSizes: ItemSize[] = [
  { id: "size_reg", name: "Regular", priceModifier: 0.0 },
  { id: "size_lg", name: "Large", priceModifier: 2.0 },
];
const burgerAddOns: AddOn[] = [
  { id: "addon_onion", name: "Extra onions", price: 1.0 },
  { id: "addon_cheese", name: "Extra Cheese", price: 1.5 },
  { id: "addon_egg", name: "Extra Fried Egg", price: 2.0 },
];

export const MOCK_MENU_ITEMS: MenuItemType[] = [
  // --- Main Course ---
  {
    id: "1",
    name: "Classic Burger",
    description:
      "Features with two juicy chicken patties, melted cheese, crisp lettuce, fresh tomatoes, etc. Perfect for those who crave a hearty, flavorful bite!",
    price: 9.99,
    image: "classic_burger.png",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    sizes: standardSizes,
    addOns: burgerAddOns,
  },
  {
    id: "2",
    name: "BBQ Bacon Burger",
    price: 12.99,
    image: "bbq_bacon_burger.png",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
    availableDiscount: fifteenPercentOff,
  },
  {
    id: "3",
    name: "Vegan Wrap",
    price: 8.99,
    image: "vegan_wrap.png",
    meal: ["Lunch", "Dinner"],
    category: "Main Course",
  },
  {
    id: "4",
    name: "Margherita Pizza",
    price: 14.5,
    image: "margherita_pizza.png",
    meal: ["Dinner", "Specials"],
    category: "Main Course",
  },
  // --- Appetizers ---
  {
    id: "5",
    name: "Chicken Caesar Salad",
    price: 7.5,
    image: "chicken_caesar_salad.png",
    meal: ["Lunch", "Dinner"],
    category: "Appetizers",
  },
  // --- Sides ---
  {
    id: "6",
    name: "French Fries",
    price: 3.99,
    image: "french_fries.png",
    meal: ["Lunch", "Dinner", "Brunch"],
    category: "Sides",
  },
  {
    id: "7",
    name: "Onion Rings",
    price: 4.99,
    image: "onion_rings.png",
    meal: ["Lunch", "Dinner"],
    category: "Sides",
  },
  // --- Drinks ---
  {
    id: "8",
    name: "Coca-Cola",
    price: 1.99,
    image: "coke.png",
    meal: ["Lunch", "Dinner", "Brunch", "Specials"],
    category: "Drinks",
  },
  {
    id: "9",
    name: "Sprite",
    price: 1.99,
    image: "sprite.png",
    meal: ["Lunch", "Dinner", "Brunch", "Specials"],
    category: "Drinks",
  },
  // --- Desserts ---
  {
    id: "10",
    name: "Chocolate Lava Cake",
    price: 6.99,
    image: "chocolate_cake.png",
    meal: ["Dinner"],
    category: "Dessert",
  },
  {
    id: "11",
    name: "New York Cheesecake",
    price: 7.25,
    image: "cheesecake.png",
    meal: ["Dinner"],
    category: "Dessert",
  },
  // --- Brunch ---
  {
    id: "12",
    name: "Fluffy Pancakes",
    price: 8.5,
    image: "pancakes.png",
    meal: ["Brunch", "Specials"],
    category: "Main Course",
    availableDiscount: tenPercentOff,
  },
  {
    id: "13",
    name: "Eggs Benedict",
    price: 10.5,
    image: "eggs_benedict.png",
    meal: ["Brunch"],
    category: "Main Course",
  },
];

export const MOCK_TABLES: TableType[] = [
  // Top Row (Circles)
  {
    id: "8",
    name: "Table 8",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 40,
    y: 40,
  },
  {
    id: "7",
    name: "Table 7",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 160,
    y: 40,
  },
  {
    id: "6",
    name: "Table 6",
    status: "In Use",
    capacity: 2,
    shape: "circle",
    x: 280,
    y: 40,
    order: { id: "#...", customerName: "...", total: 55 },
  },
  {
    id: "5",
    name: "Table 5",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 400,
    y: 40,
  },
  {
    id: "1",
    name: "Table 1",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 600,
    y: 40,
  },
  {
    id: "2",
    name: "Table 2",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 720,
    y: 40,
  },
  // Second Row
  {
    id: "4",
    name: "Table 4",
    status: "Available",
    capacity: 4,
    shape: "square",
    x: 600,
    y: 150,
  },
  {
    id: "3",
    name: "Table 3",
    status: "Needs Cleaning",
    capacity: 4,
    shape: "square",
    x: 720,
    y: 150,
  },
  // Middle Rows (Squares)
  {
    id: "10",
    name: "Table 10",
    status: "Needs Cleaning",
    capacity: 4,
    shape: "square",
    x: 200,
    y: 250,
  },
  {
    id: "9",
    name: "Table 9",
    status: "In Use",
    capacity: 4,
    shape: "square",
    x: 350,
    y: 250,
    order: { id: "#...", customerName: "...", total: 82 },
  },
  {
    id: "11",
    name: "Table 11",
    status: "Available",
    capacity: 4,
    shape: "square",
    x: 200,
    y: 350,
  },
  {
    id: "12",
    name: "Table 12",
    status: "Available",
    capacity: 4,
    shape: "square",
    x: 350,
    y: 350,
  },
  {
    id: "13",
    name: "Table 13",
    status: "Available",
    capacity: 6,
    shape: "square",
    x: 660,
    y: 280,
  },
  {
    id: "14",
    name: "Table 14",
    status: "Needs Cleaning",
    capacity: 6,
    shape: "square",
    x: 660,
    y: 380,
  },
  {
    id: "15",
    name: "Table 15",
    status: "Available",
    capacity: 6,
    shape: "square",
    x: 660,
    y: 480,
  },
  // Bottom Row (Circles)
  {
    id: "21",
    name: "Table 21",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 200,
    y: 600,
  },
  {
    id: "20",
    name: "Table 20",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 320,
    y: 600,
  },
  {
    id: "19",
    name: "Table 19",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 440,
    y: 600,
  },
  {
    id: "18",
    name: "Table 18",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 560,
    y: 600,
  },
  {
    id: "17",
    name: "Table 17",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 680,
    y: 600,
  },
  {
    id: "16",
    name: "Table 16",
    status: "Available",
    capacity: 2,
    shape: "circle",
    x: 800,
    y: 600,
  },
];

export const PARTNER_LOGO_MAP = {
  "Door Dash": require("@/assets/images/doordash.png"),
  grubhub: require("@/assets/images/grubhub.png"),
  "Uber-Eats": require("@/assets/images/uber-eats.png"),
  "Food Panda": require("@/assets/images/food-panda.png"),
};

const sampleOrderItems: CartItem[] = [
  {
    id: "burger_1",
    menuItemId: "1",
    name: "Double Cheeseburger",
    quantity: 1,
    originalPrice: 7.25,
    finalPrice: 13.25,
    customizations: {
      size: { id: "size_lg", name: "Large", priceModifier: 2.0 },
      addOns: [
        { id: "addon_onion", name: "Extra onions", price: 1.0 },
        { id: "addon_cheese", name: "Extra Cheese", price: 1.5 },
        { id: "addon_egg", name: "Extra Fried Egg", price: 1.5 },
      ],
      notes: "Make the cheese more melted",
    },
    image: "classic_burger.png",
  },
  {
    id: "burger_2",
    menuItemId: "1",
    name: "Double Cheeseburger",
    quantity: 1,
    originalPrice: 7.25,
    finalPrice: 7.25,
    customizations: {
      size: { id: "size_reg", name: "Regular", priceModifier: 0 },
    },
    image: "classic_burger.png",
  },
  {
    id: "coke_1",
    menuItemId: "8",
    name: "Coca-Cola",
    quantity: 1,
    originalPrice: 1.99,
    finalPrice: 1.99,
    customizations: {},
    image: "coke.png",
  },
];

export const MOCK_ONLINE_ORDERS: OnlineOrder[] = [
  // Add a variety of orders with different statuses and partners
  {
    id: "#45654",
    status: "New Orders",
    deliveryPartner: "Door Dash",
    customerName: "John Jones",
    total: 520,
    itemCount: 10,
    timestamp: "02/03/25, 05:36 PM",
    customerDetails: {
      id: "#54568",
      phone: "+560934856",
      email: "john@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45655",
    status: "New Orders",
    deliveryPartner: "Uber-Eats",
    customerName: "Jane Smith",
    total: 350,
    itemCount: 5,
    timestamp: "02/03/25, 05:38 PM",
    customerDetails: {
      id: "#54569",
      phone: "+123456789",
      email: "jane@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45656",
    status: "Confirmed/In-Process",
    deliveryPartner: "Food Panda",
    customerName: "Alex Ray",
    total: 410,
    itemCount: 8,
    timestamp: "02/03/25, 05:30 PM",
    customerDetails: {
      id: "#54570",
      phone: "+987654321",
      email: "alex@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45657",
    status: "Confirmed/In-Process",
    deliveryPartner: "grubhub",
    customerName: "Emily Clark",
    total: 600,
    itemCount: 12,
    timestamp: "02/03/25, 05:25 PM",
    customerDetails: {
      id: "#54571",
      phone: "+555555555",
      email: "emily@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45658",
    status: "Ready to Dispatch",
    deliveryPartner: "Uber-Eats",
    customerName: "Michael Bee",
    total: 220,
    itemCount: 3,
    timestamp: "02/03/25, 05:20 PM",
    customerDetails: {
      id: "#54572",
      phone: "+444444444",
      email: "michael@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
  {
    id: "#45659",
    status: "Dispatched",
    deliveryPartner: "Food Panda",
    customerName: "Sarah Day",
    total: 750,
    itemCount: 15,
    timestamp: "02/03/25, 05:15 PM",
    customerDetails: {
      id: "#54573",
      phone: "+666666666",
      email: "sarah@gmail.com",
    },
    paymentStatus: "Paid",
    items: sampleOrderItems,
  },
];

export const MOCK_PREVIOUS_ORDERS: PreviousOrder[] = [
  {
    serialNo: "001",
    orderDate: "Oct 16, 2024",
    orderTime: "09:31 AM",
    orderId: "#2010E10",
    paymentStatus: "In Progress",
    server: "Jake Carter",
    itemCount: 5,
    type: "Dine In",
    total: 34.5,
    items: sampleOrderItems,
  },
  {
    serialNo: "002",
    orderDate: "Oct 16, 2024",
    orderTime: "09:35 AM",
    orderId: "#2010E11",
    paymentStatus: "Paid",
    server: "Jessica",
    itemCount: 3,
    type: "Takeout",
    total: 22.75,
    items: [],
  },
  {
    serialNo: "003",
    orderDate: "Oct 16, 2024",
    orderTime: "09:40 AM",
    orderId: "#2010E12",
    paymentStatus: "Paid",
    server: "Jake Carter",
    itemCount: 8,
    type: "Delivery",
    total: 105.25,
    items: sampleOrderItems,
  },
  {
    serialNo: "004",
    orderDate: "Oct 15, 2024",
    orderTime: "08:15 PM",
    orderId: "#2009E95",
    paymentStatus: "Refunded",
    server: "Jessica",
    itemCount: 2,
    type: "Dine In",
    total: 15.0,
    items: [],
  },
  // Add 5-10 more mock orders to make the list feel full
];

export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "#2020E11",
    serialNo: "001",
    name: "Blueberry Muffin",
    image: require("@/assets/images/blueberry_muffin.png"),
    description: "Savory pastries filled with a blend of cheeses and herbs...",
    stock: 250,
    unit: "PCs",
    lastUpdate: "02/03/2025 10:30 AM",
    status: "Inactive",
    category: "Pastries",
    modifier: "None",
    availability: false,
  },
  {
    id: "#2040E13",
    serialNo: "002",
    name: "Sourdough Bread",
    image: require("@/assets/images/sourdough_bread.png"),
    description: "Artisan sourdough loaves with a crunchy crust...",
    stock: 250,
    unit: "PCs",
    lastUpdate: "02/03/2025 10:30 AM",
    status: "Draft",
    category: "Breads",
    modifier: "None",
    availability: true,
  },
  {
    id: "#2030E12",
    serialNo: "003",
    name: "Chocolate Croissant",
    image: require("@/assets/images/chocolate_croissant.png"),
    description: "Chocolate croissants with a rich, buttery flake...",
    stock: 250,
    unit: "PCs",
    lastUpdate: "02/03/2025 10:30 AM",
    status: "Active",
    category: "Pastries",
    modifier: "Chocolate",
    availability: true,
  },
  {
    id: "#2050E14",
    serialNo: "004",
    name: "Multigrain Bread",
    image: require("@/assets/images/multigrain_bread.png"),
    description: "Hearty multigrain bread packed with seeds...",
    stock: 0,
    unit: "PCs",
    lastUpdate: "02/03/2025 10:30 AM",
    status: "Out of Stock",
    category: "Breads",
    modifier: "None",
    availability: true,
  },
  {
    id: "#2080E17",
    serialNo: "005",
    name: "Fresh Baked Buns",
    image: require("@/assets/images/fresh_baked_buns.png"),
    description: "Flaky biscuit rounds, light and airy, ideal for breakfast.",
    stock: 250,
    unit: "PCs",
    lastUpdate: "02/03/2025 10:30 AM",
    status: "Active",
    category: "Breads",
    modifier: "None",
    availability: true,
  },
  {
    id: "#2090E18",
    serialNo: "006",
    name: "Cinnamon Roll",
    image: require("@/assets/images/cinnamon_roll.png"),
    description: "Delightful muffins bursting with seasonal fruits.",
    stock: 250,
    unit: "PCs",
    lastUpdate: "02/03/2025 10:30 AM",
    status: "Active",
    category: "Pastries",
    modifier: "Glaze",
    availability: true,
  },
  {
    id: "#2060E15",
    serialNo: "007",
    name: "Flaky Biscuit",
    image: require("@/assets/images/flaky_biscuit.png"),
    description: "Sweet cinnamon rolls drizzled with cream cheese icing.",
    stock: 0,
    unit: "PCs",
    lastUpdate: "02/03/2025 10:30 AM",
    status: "Out of Stock",
    category: "Pastries",
    modifier: "None",
    availability: true,
  },
  {
    id: "#2070E16",
    serialNo: "008",
    name: "Sesame Bagel",
    image: require("@/assets/images/sesame_bagel.png"),
    description:
      "Classic bagels, boiled and baked to achieve the perfect chewy texture.",
    stock: 0,
    unit: "PCs",
    lastUpdate: "02/03/2025 10:30 AM",
    status: "Out of Stock",
    category: "Breads",
    modifier: "Cream Cheese",
    availability: true,
  },
];

export const MOCK_USER_PROFILE: UserProfile = {
  id: "#54568",
  employeeId: "JS002T",
  fullName: "Tom Hardy",
  dob: "04/09/1996",
  gender: "Male",
  country: "USA",
  address: "New York, USA",
  email: "tom@gmail.com",
  phone: "+8037247534858347",
  pin: "498843",
  profileImageUrl: "tom_hardy.jpg",
};

export const MOCK_SHIFT_STATUS: ShiftStatus = {
  status: "Clocked In",
  duration: "5 h 24 m",
  clockInTime: "08:01 AM",
};

export const MOCK_SHIFT_HISTORY: ShiftHistoryEntry[] = Array.from(
  { length: 7 },
  (_, i) => ({
    id: i.toString(),
    date: "02/03/2025",
    clockIn: "10:30 AM",
    breakInitiated: "12:30 PM",
    breakEnded: "01:30 PM",
    clockOut: "06:30 PM",
    duration: "8h 11m",
  })
);

export const MOCK_PRINTERS: PrinterDevice[] = [
  {
    id: "1",
    name: "Receipt Printer",
    isEnabled: true,
    status: "Connected",
    connectionType: "Wi-Fi",
    ipAddress: "192.168.1.101",
  },
  {
    id: "2",
    name: "Kitchen Printer",
    isEnabled: true,
    status: "Disconnected",
    connectionType: "Wi-Fi",
    ipAddress: "192.168.1.102",
  },
  {
    id: "3",
    name: "Bar Printer",
    isEnabled: false,
    status: "Disconnected",
    connectionType: "Bluetooth",
  },
];

export const MOCK_CATEGORIES = [
  { label: "Food", value: "Food" },
  { label: "Drinks", value: "Drinks" },
  { label: "Desserts", value: "Desserts" },
  { label: "Appetizers", value: "Appetizers" },
];

export const MOCK_PRINTER_RULES: PrinterRule[] = [
  {
    id: "rule1",
    isEnabled: true,
    category: "Food",
    printerId: MOCK_PRINTERS[0].id,
  },
  {
    id: "rule2",
    isEnabled: false,
    category: "Drinks",
    printerId: MOCK_PRINTERS[2].id,
  },
  {
    id: "rule3",
    isEnabled: false,
    category: "Desserts",
    printerId: MOCK_PRINTERS[1].id,
  },
];

export const MOCK_TERMINALS: PaymentTerminal[] = [
  {
    id: "TRM00123",
    name: "Terminal A-123",
    isEnabled: true,
    status: "Connected",
    batteryLevel: 85,
  },
  {
    id: "TRM00124",
    name: "Terminal B-124",
    isEnabled: true,
    status: "Disconnected",
    batteryLevel: 62,
  },
  {
    id: "TRM00234",
    name: "Terminal D-234",
    isEnabled: false,
    status: "Disconnected",
    batteryLevel: 45,
  },
];

export const MOCK_FOUND_TERMINALS = [
  { id: "Epson-TM", name: "Epson TM-m30II-NT" },
  { id: "PIXMA-E3470", name: "PIXMA E3470" },
  { id: "HP-9025", name: "HP OfficeJet Pro 9025" },
  { id: "Canon-TR4520", name: "Canon PIXMA TR4520" },
  { id: "Brother-HL", name: "Brother HL-L2390DW" },
];

export const MOCK_OFFLINE_ORDERS: OfflineOrder[] = Array(8).fill({
  serialNo: "001",
  orderDate: "Oct 16, 2024",
  orderTime: "09:31 AM",
  orderId: "#2010E10",
  server: "Jake Carter",
  total: 34.5,
});

export const salesData = [
  { hour: 6, today: 180, yesterday: 320 },
  { hour: 8, today: 250, yesterday: 410 },
  { hour: 10, today: 310, yesterday: 240 },
  { hour: 12, today: 190, yesterday: 445 },
  { hour: 14, today: 360, yesterday: 330 },
  { hour: 16, today: 420, yesterday: 290 },
  { hour: 18, today: 320, yesterday: 500 },
  { hour: 20, today: 380, yesterday: 240 },
];

// Mock data for the "Open vs Closed Checks" donut chart
export const checksData = [
  { x: "Open", y: 22.19 },
  { x: "Closed", y: 77.81 },
];

// Mock data for the "Check Status Overview" donut chart
export const checkStatusData = [
  { x: "Completed", y: 56.2 },
  { x: "Pending", y: 34.5 },
  { x: "In Progress", y: 9.3 },
];

// Mock data for the "Top Selling Items" bar chart
export const topItemsData = [
  { name: "Crispy Cheese Burger", quantity: 18 },
  { name: "Chicken Alfredo Pasta", quantity: 13 },
  { name: "Spicy Chicken Burger", quantity: 10 },
  { name: "Beef Shawarma Wrap", quantity: 9 },
  { name: "BBQ Chicken Wings", quantity: 7 },
];
