export const kioskStrings = {
  attractTitle: "Ready when you are",
  startOrder: "Tap to order",
  dineIn: "Dine in",
  takeOut: "Take out",
  chooseOrderType: "How would you like your order?",
  browseMenu: "Browse menu",
  allItems: "All items",
  cart: "Cart",
  addToCart: "Add to cart",
  done: "Done",
  updateCart: "Update cart",
  quantity: "Quantity",
  emptyCart: "Your cart is empty",
  continue: "Continue",
  back: "Back",
  checkout: "Checkout",
  loyaltyTitle: "Loyalty",
  loyaltyPrompt: "Enter your phone number for rewards",
  skip: "Skip",
  tipTitle: "Add a tip",
  paymentTitle: "Payment",
  paymentMock: "Payment handoff is mocked for this sprint",
  confirmationTitle: "Order received",
  confirmationBody: "Your kiosk order flow is ready for payment integration.",
  reset: "Start over",
  removeUnavailableTitle: "Item unavailable",
  removeUnavailableBody: "One item is no longer available and was removed from your cart.",
  templateSwitcher: "Template",
} as const;

export type KioskStringKey = keyof typeof kioskStrings;
